name: Foundations Bugs hourly sync

on:
  workflow_dispatch: # Enables manual triggers
#  schedule:
    # Runs the workflow every hour (at minute 0)
#    - cron: '0 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python 
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies and project
      - name: Pip Install
        run: |
          pip install jira
          pip install .

      - name: Install jq
        run: sudo apt-get install -y jq


      - name: Set up Jira API Token and Team JSON Files
        run: |
          # Write secrets to files
          printf "%s" "${{ secrets.TEAM_MEMBERS_JSON }}" > team_members.json
          printf "%s" "${{ secrets.JIRA_API_TOKEN }}" > jira_api.json

          # Check file existence and size
          echo "Checking file existence and size:"
          ls -l team_members.json jira_api.json

          od -c team_members.json
          od -c jira_api.json

          # Validate JSON structure for team_members.json
          echo "Validating JSON structure:"
          jq empty team_members.json || echo "team_members.json is not valid JSON"

          # If JIRA_API_TOKEN is JSON (adjust depending on its content)
          echo "Validating JIRA API Token structure (if applicable):"
          jq empty jira_api.json || echo "jira_api.json is not valid JSON"

      # Run the command 
      # test lp-to-jira-sync
      - name: Test run
        run: |
          lp-to-jira-sync -p FR -t foundations-todo -T foundations-bugs \
          -i team_members.json -j jira_api.json \
          -c samples/foundations_packages_components_mapping.json \
          --dry-run